[project]
name = "empleabilidad_app"
version = "0.1.0"
description = "Plataforma de empleabilidad"
authors = [{ name = "Tu Nombre"}]
dependencies = []

[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"
